version: "3"
services:
  hugo:
    build: hugo
    environment:
      LANG: ja_JP.utf8
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ..:/workspace
    tty: true
